//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grievance.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTransaction
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public string UserId { get; set; }
        public string Operation { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    }
}
